content:
  - type: collection
    label: "words"
    name: "words"
    path: "content/words"
    fields:
      - { label: "Title", name: "title", type: "string" }
      - { label: "Publish date", name: "date", type: "date" }
      - { label: "Description", name: "description", type: "string" }
      - { label: "Tags", name: "tags", type: "select"}
      - { label: "Body", name: "body", type: "rich-text" }
  - type: collection
    label: "supper clubs"
    name: "supperclubs"
    path: "content/supperclubs"
    fields:
      - { label: "Title", name: "title", type: "string" }
      - { label: "Publish date", name: "date", type: "date" }
      - { label: "Event type", name: "eventtype", type: "select" }
      - { label: "Description", name: "description", type: "string" }
      - { label: "Active", name: "active", type: "boolean" }
      - { label: "Tags", name: "tags", type: "select"}
      - { label: "Body", name: "body", type: "rich-text" }
  - type: collection
    label: "recipes"
    name: "recipes"
    path: "content/recipes"
    fields:
      - { label: "Title", name: "title", type: "string" }
      - { label: "Created", name: "created", type: "date" }
      - { label: "Modified", name: "modified", type: "date" }
      - { label: "Source", name: "source", type: "string" }
      - { label: "Image", name: "image", type: "image" }
      - { label: "Body", name: "body", type: "rich-text" }
media:
  input: "static/images"
  output: "/images"